[package]
name = "cool-thing"
version = "0.1.0"
authors = ["Ivan Nikulin <inikulin@cloudflare.com>"]
autotests = false

[lib]
doctest = false

[features]
trace_actions = []
trace_char = []
trace_raw = []

[[test]]
harness = false
name = "main"

[dev-dependencies]
getopts = "0.2.15"
glob = "0.2.11"
html5ever = "0.21.0"
serde = "1.0.19"
serde_derive = "1.0.19"
serde_json = "1.0.5"
pre-commit = "0.5.2"

[package.metadata.precommit]
fmt = "cargo fmt && git add -u"

[dev-dependencies.rustc-test]
version = "0.2.0"

