[package]
name = "cool_thing_c_api"
version = "0.1.0"
authors = ["Ivan Nikulin <inikulin@cloudflare.com>"]
edition = "2018"

[dependencies]
cool_thing = { path = "../" }

[profile.release]
panic = "abort"
lto = true

[lib]
crate-type = ["staticlib"]